package de.simon.dankelmann.bluetoothlespam.Enums

enum class AdvertisementSetType {
    ADVERTISEMENT_TYPE_UNDEFINED,
    ADVERTISEMENT_TYPE_FAST_PAIRING,
    ADVERTISEMENT_TYPE_FAST_PAIRING_DEBUG,
    ADVERTISEMENT_TYPE_CONTINUITY_DEVICE_POPUPS,
    ADVERTISEMENT_TYPE_CONTINUITY_ACTION_MODALS,
    ADVERTISEMENT_TYPE_SWIFT_PAIRING,
    ADVERTISEMENT_TYPE_EASY_SETUP
}