package de.simon.dankelmann.bluetoothlespam.Enums

enum class AdvertisementTarget {
    ADVERTISEMENT_TARGET_KITCHEN_SINK,
    ADVERTISEMENT_TARGET_UNDEFINED,
    ADVERTISEMENT_TARGET_ANDROID,
    ADVERTISEMENT_TARGET_IOS,
    ADVERTISEMENT_TARGET_WINDOWS,
    ADVERTISEMENT_TARGET_SAMSUNG,
    ADVERTISEMENT_TARGET_LOVESPOUSE
}