package de.simon.dankelmann.bluetoothlespam.Enums

enum class AdvertisementSetType {
    ADVERTISEMENT_TYPE_UNDEFINED,
    ADVERTISEMENT_TYPE_FAST_PAIRING_DEVICE,
    ADVERTISEMENT_TYPE_FAST_PAIRING_NON_PRODUCTION,
    ADVERTISEMENT_TYPE_FAST_PAIRING_PHONE_SETUP,
    ADVERTISEMENT_TYPE_FAST_PAIRING_DEBUG,
    ADVERTISEMENT_TYPE_CONTINUITY_DEVICE_POPUPS,
    ADVERTISEMENT_TYPE_CONTINUITY_ACTION_MODALS,
    ADVERTISEMENT_TYPE_CONTINUITY_IOS_17_CRASH,
    ADVERTISEMENT_TYPE_SWIFT_PAIRING,
    ADVERTISEMENT_TYPE_EASY_SETUP_WATCH,
    ADVERTISEMENT_TYPE_EASY_SETUP_BUDS,
    ADVERTISEMENT_TYPE_LOVESPOUSE_PLAY,
    ADVERTISEMENT_TYPE_LOVESPOUSE_STOP
}