package de.simon.dankelmann.bluetoothlespam.Enums

enum class AdvertisementError {
    ADVERTISE_FAILED_UNKNOWN,
    ADVERTISE_FAILED_ALREADY_STARTED,
    ADVERTISE_FAILED_DATA_TOO_LARGE,
    ADVERTISE_FAILED_FEATURE_UNSUPPORTED,
    ADVERTISE_FAILED_INTERNAL_ERROR,
    ADVERTISE_FAILED_TOO_MANY_ADVERTISERS
}